"""
3D 生成 API 路由
3D Generation API endpoints
"""
from fastapi import APIRouter, UploadFile, File, HTTPException, BackgroundTasks, Depends
from fastapi.responses import FileResponse
from typing import Optional
import uuid
import os
from pathlib import Path
import logging

from app.services.generation.hunyuan3d_service import get_hunyuan3d_service, Hunyuan3DService
from app.services.generation.sf3d_service import get_sf3d_service, SF3DService
from app.services.generation.triposr_service import get_triposr_service, TripoSRService
from app.services.generation.instantmesh_service import get_instantmesh_service, InstantMeshService
from app.models.model import Model3D
from app.database import get_db
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/generation", tags=["generation"])

# 临时存储目录
UPLOAD_DIR = Path("uploads/generation")
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)


@router.post("/upload")
async def upload_and_generate(
    file: UploadFile = File(...),
    enable_texture: bool = False,
    steps: int = 30,
    guidance_scale: float = 7.5,
    seed: int = 1234,
    octree_resolution: int = 256,
    remove_background: bool = True,
    background_tasks: BackgroundTasks = None,
    db: AsyncSession = Depends(get_db)
):
    """
    上传图片并生成 3D 模型 (Hunyuan3D)
    
    - 接收 JPG/PNG 图片
    - 提交到 Hunyuan3D 进行推理
    - 返回任务 ID
    """
    # 1. 验证文件类型
    if not file.content_type or not file.content_type.startswith('image/'):
        raise HTTPException(status_code=400, detail="Only image files are allowed")
    
    # 2. 保存图片
    file_ext = file.filename.split('.')[-1] if '.' in file.filename else 'jpg'
    temp_path = UPLOAD_DIR / f"{uuid.uuid4()}.{file_ext}"
    
    try:
        with open(temp_path, 'wb') as buffer:
            content = await file.read()
            buffer.write(content)
        
        logger.info(f"Image saved to: {temp_path}")
        
        # 3. 提交生成任务
        service = get_hunyuan3d_service()
        
        # 根据模式处理
        if service.mode == "cloud":
            # 云端模式：同步等待云端API完成
            logger.info(f"[API] Using cloud mode for generation")
            try:
                result = await service.generate_from_image(
                    image_path=str(temp_path),
                    enable_texture=enable_texture
                )
                
                if result.get('status') == 'completed':
                    # 保存到数据库
                    model = Model3D(
                        name=f"Cloud Model {result['uid'][:8]}",
                        description="Generated by Tencent Hunyuan3D Cloud API",
                        category="other",
                        status="completed",
                        model_url=result['glb_path'],
                        format="glb",
                        file_size=0,  # TODO: 获取实际文件大小
                        generation_engine="hunyuan3d-cloud",
                        created_by=None
                    )
                    db.add(model)
                    await db.commit()
                    await db.refresh(model)
                    
                    return {
                        "uid": result["uid"],
                        "status": "completed",
                        "message": "Cloud generation completed successfully!",
                        "model_id": model.id,
                        "generation_time": result.get('generation_time', 0)
                    }
                else:
                    # 生成失败
                    raise HTTPException(
                        status_code=500,
                        detail=f"Cloud generation failed: {result.get('error', 'Unknown error')}"
                    )
            except HTTPException:
                raise
            except Exception as e:
                logger.error(f"Cloud generation error: {e}", exc_info=True)
                raise HTTPException(status_code=500, detail=f"Cloud generation failed: {str(e)}")
        
        elif service.mode == "mock":
            # Mock模式：跳过健康检查，直接模拟
            logger.info(f"[API] Using mock mode for generation")
            result = await service.generate_from_image(
                image_path=str(temp_path),
                enable_texture=enable_texture
            )
            
            # Mock模式立即返回，前端轮询等待
            if background_tasks:
                background_tasks.add_task(
                    process_generation_result,
                    uid=result["uid"],
                    image_path=str(temp_path),
                    db=db
                )
            
            return {
                "uid": result["uid"],
                "status": "processing",
                "message": "Mock generation started. Will complete in 5 seconds."
            }
        
        else:
            # Local模式或其他模式
            logger.info(f"[API] Using {service.mode} mode for generation")
            result = await service.generate_from_image(
                image_path=str(temp_path),
                enable_texture=enable_texture
            )
            
            # 在后台等待完成并保存
            if background_tasks:
                background_tasks.add_task(
                    process_generation_result,
                    uid=result["uid"],
                    image_path=str(temp_path),
                    db=db
                )
            
            return {
                "uid": result["uid"],
                "status": "processing",
                "message": "Generation started. Use /status/{uid} to check progress."
            }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Generation failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Generation failed: {str(e)}")


@router.get("/status/{uid}")
async def get_generation_status(uid: str):
    """查询生成状态"""
    try:
        service = get_hunyuan3d_service()
        status = await service.check_status(uid)
        return status
    except Exception as e:
        logger.error(f"Status check failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/download/{uid}")
async def download_model(uid: str):
    """下载生成的 GLB 模型"""
    try:
        # 根据 uid 前缀选择对应的服务
        service = None
        if uid.startswith("sf3d_"):
            service = get_sf3d_service()
        elif uid.startswith("triposr_"):
            service = get_triposr_service()
        elif uid.startswith("instantmesh_"):
            service = get_instantmesh_service()
        else:
            # 默认使用 Hunyuan3D
            service = get_hunyuan3d_service()
        
        status = await service.check_status(uid)
        
        if status["status"] != "completed":
            raise HTTPException(status_code=404, detail="Model not ready yet")
        
        glb_path = status.get("glb_path")
        if not glb_path or not os.path.exists(glb_path):
            logger.error(f"Model file not found: {glb_path}")
            raise HTTPException(status_code=404, detail="Model file not found")
        
        logger.info(f"Downloading model: {glb_path}")
        return FileResponse(
            path=glb_path,
            filename=f"model_{uid}.glb",
            media_type="model/gltf-binary"
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Download failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


async def process_generation_result(
    uid: str,
    image_path: str,
    db: AsyncSession
):
    """
    后台处理生成结果
    
    1. 等待生成完成
    2. 上传到 OSS（可选）
    3. 保存到数据库
    4. 清理临时文件
    """
    try:
        service = get_hunyuan3d_service()
        
        # 等待完成（最多等待 5 分钟）
        glb_path = await service.wait_for_completion(uid, max_wait_time=300.0)
        
        logger.info(f"Model generated: {glb_path}")
        
        # TODO: 上传到 OSS
        # oss_url = await upload_to_oss(glb_path)
        
        # 保存到数据库
        model = Model3D(
            name=f"AI Generated Model {uid[:8]}",
            description="Generated by Hunyuan3D-2mini",
            category="other",
            status="approved",  # 自动审核通过
            model_url=glb_path,  # 或 OSS URL
            format="glb",
            file_size=os.path.getsize(glb_path) if os.path.exists(glb_path) else 0,
            generation_engine="hunyuan3d",
            created_by=None  # TODO: 从上下文获取用户 ID
        )
        
        db.add(model)
        await db.commit()
        await db.refresh(model)
        
        logger.info(f"Model saved to database: {model.id}")
        
        # 清理临时图片
        if os.path.exists(image_path):
            os.remove(image_path)
            logger.info(f"Temporary image removed: {image_path}")
        
    except Exception as e:
        logger.error(f"Failed to process generation result: {e}", exc_info=True)
        # TODO: 更新任务状态为失败


# ==================== SF3D Generation ====================

@router.post("/sf3d/upload")
async def sf3d_upload_and_generate(
    file: UploadFile = File(...),
):
    """
    SF3D生成 - 极速高质量3D生成 (~0.5秒)
    
    - GitHub: https://github.com/Stability-AI/generative-models
    - 速度: ~0.5秒 | 显存: 9GB | 许可证: Apache-2.0
    """
    if not file.content_type or not file.content_type.startswith('image/'):
        raise HTTPException(status_code=400, detail="Only image files are allowed")
    
    file_ext = file.filename.split('.')[-1] if '.' in file.filename else 'jpg'
    temp_path = UPLOAD_DIR / f"sf3d_{uuid.uuid4()}.{file_ext}"
    
    try:
        with open(temp_path, 'wb') as buffer:
            content = await file.read()
            buffer.write(content)
        
        service = get_sf3d_service()
        result = await service.generate_from_image(str(temp_path))
        
        return {
            "uid": result["uid"],
            "status": result["status"],
            "generation_time": result.get("generation_time"),
            "warning": result.get("warning")
        }
    except Exception as e:
        logger.error(f"SF3D generation failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


# ==================== TripoSR Generation ====================

@router.post("/triposr/upload")
async def triposr_upload_and_generate(
    file: UploadFile = File(...),
):
    """
    TripoSR生成 - 超快概念验证 (<1秒)
    
    - GitHub: https://github.com/VAST-AI-Research/TripoSR
    - 速度: <1秒 | 显存: 4-6GB | 许可证: MIT
    """
    if not file.content_type or not file.content_type.startswith('image/'):
        raise HTTPException(status_code=400, detail="Only image files are allowed")
    
    file_ext = file.filename.split('.')[-1] if '.' in file.filename else 'jpg'
    temp_path = UPLOAD_DIR / f"triposr_{uuid.uuid4()}.{file_ext}"
    
    try:
        with open(temp_path, 'wb') as buffer:
            content = await file.read()
            buffer.write(content)
        
        service = get_triposr_service()
        result = await service.generate_from_image(str(temp_path))
        
        return {
            "uid": result["uid"],
            "status": result["status"],
            "generation_time": result.get("generation_time"),
            "warning": result.get("warning")
        }
    except Exception as e:
        logger.error(f"TripoSR generation failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


# ==================== InstantMesh Generation ====================

@router.post("/instantmesh/upload")
async def instantmesh_upload_and_generate(
    file: UploadFile = File(...),
):
    """
    InstantMesh生成 - 精细网格生成 (10-25秒)
    
    - GitHub: https://github.com/TencentARC/InstantMesh
    - 速度: 10-25秒 | 显存: 8-12GB | 许可证: 待确认
    """
    if not file.content_type or not file.content_type.startswith('image/'):
        raise HTTPException(status_code=400, detail="Only image files are allowed")
    
    file_ext = file.filename.split('.')[-1] if '.' in file.filename else 'jpg'
    temp_path = UPLOAD_DIR / f"instantmesh_{uuid.uuid4()}.{file_ext}"
    
    try:
        with open(temp_path, 'wb') as buffer:
            content = await file.read()
            buffer.write(content)
        
        service = get_instantmesh_service()
        result = await service.generate_from_image(str(temp_path))
        
        return {
            "uid": result["uid"],
            "status": result["status"],
            "generation_time": result.get("generation_time"),
            "warning": result.get("warning")
        }
    except Exception as e:
        logger.error(f"InstantMesh generation failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
