// 画廊示例数据
import type { GalleryItem } from './gallery.types';

// ==================== 精品盒子类 ====================
const BOX_MODELS: GalleryItem[] = [
  // ========== 化妆品盒 ==========
  {
    id: 'box-1',
    title: '💄 品牌口红礼盒',
    description: '高档口红套装盒，金色烫金工艺，适合情人节礼物',
    thumbnail: 'https://picsum.photos/seed/cosmetics1/400/300',
    gifPreview: 'https://media.giphy.com/media/3o7TKP0tZ2cN5ycQk8/giphy.gif',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-18',
    views: 5670,
    likes: 445,
    tags: ['口红', '化妆品', '礼盒', '金色'],
    category: 'model',
    boxType: 'cosmetics',
    price: '¥299-899',
    material: '特种纸+烫金',
    industry: '美妆',
  },
  {
    id: 'box-2',
    title: '🧴 精华液包装盒',
    description: '高档精华液套装盒，哑光质感，简约轻奢风格',
    thumbnail: 'https://picsum.photos/seed/cosmetics2/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-17',
    views: 3450,
    likes: 278,
    tags: ['精华', '护肤品', '简约', '轻奢'],
    category: 'model',
    boxType: 'cosmetics',
    price: '¥199-599',
    material: '灰板纸+UV',
    industry: '美妆',
  },
  {
    id: 'box-3',
    title: '💅 美甲套装礼盒',
    description: '美甲工具套装盒，多层抽屉设计，少女心粉色系',
    thumbnail: 'https://picsum.photos/seed/cosmetics3/400/300',
    modelUrl: '',
    author: 'User Demo',
    createdAt: '2026-04-15',
    views: 2890,
    likes: 234,
    tags: ['美甲', '工具', '粉色', '少女'],
    category: 'model',
    boxType: 'cosmetics',
    price: '¥129-399',
    material: '白卡+覆膜',
    industry: '美妆',
  },
  {
    id: 'box-4',
    title: '🌸 香氛蜡烛礼盒',
    description: '香氛蜡烛套装盒，渐变色彩包装，营造浪漫氛围',
    thumbnail: 'https://picsum.photos/seed/cosmetics4/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-12',
    views: 4120,
    likes: 356,
    tags: ['香氛', '蜡烛', '浪漫', '家居'],
    category: 'model',
    boxType: 'cosmetics',
    price: '¥159-459',
    material: '特种纸+烫银',
    industry: '美妆',
  },

  // ========== 高档酒盒 ==========
  {
    id: 'box-5',
    title: '🍷 红酒礼盒',
    description: '高档红酒礼盒，木质底座+烫金工艺，彰显品质',
    thumbnail: 'https://picsum.photos/seed/wine1/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-16',
    views: 6780,
    likes: 534,
    tags: ['红酒', '酒盒', '木质', '高档'],
    category: 'model',
    boxType: 'wine',
    price: '¥299-1999',
    material: '木质+烫金',
    industry: '酒类',
  },
  {
    id: 'box-6',
    title: '🥃 威士忌礼盒',
    description: '单一麦芽威士忌礼盒，金属质感+皮质内衬，绅士之选',
    thumbnail: 'https://picsum.photos/seed/wine2/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-14',
    views: 5230,
    likes: 423,
    tags: ['威士忌', '酒盒', '金属', '绅士'],
    category: 'model',
    boxType: 'wine',
    price: '¥599-2999',
    material: '金属+皮质',
    industry: '酒类',
  },
  {
    id: 'box-7',
    title: '🍶 白酒礼盒',
    description: '高档白酒礼盒，中国风设计，传统文化元素',
    thumbnail: 'https://picsum.photos/seed/wine3/400/300',
    modelUrl: '',
    author: 'User Demo',
    createdAt: '2026-04-10',
    views: 4560,
    likes: 389,
    tags: ['白酒', '中国风', '传统', '文化'],
    category: 'model',
    boxType: 'wine',
    price: '¥399-1599',
    material: '特种纸+UV',
    industry: '酒类',
  },
  {
    id: 'box-8',
    title: '🍾 香槟礼盒',
    description: '年份香槟礼盒，节日庆典首选，金色气泡元素',
    thumbnail: 'https://picsum.photos/seed/wine4/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-08',
    views: 3890,
    likes: 312,
    tags: ['香槟', '庆典', '金色', '节日'],
    category: 'model',
    boxType: 'wine',
    price: '¥499-2499',
    material: '特种纸+烫金',
    industry: '酒类',
  },

  // ========== 礼品盒 ==========
  {
    id: 'box-9',
    title: '🎁 珠宝首饰盒',
    description: '高档珠宝礼盒，天鹅绒内衬，钻石切面外观设计',
    thumbnail: 'https://picsum.photos/seed/gift1/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-15',
    views: 7890,
    likes: 678,
    tags: ['珠宝', '首饰', '高档', '天鹅绒'],
    category: 'model',
    boxType: 'gift',
    price: '¥199-999',
    material: '木板+绒布',
    industry: '珠宝',
  },
  {
    id: 'box-10',
    title: '⌚ 手表礼盒',
    description: '机械表礼盒，磁吸开合设计，高端商务风格',
    thumbnail: 'https://picsum.photos/seed/gift2/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-13',
    views: 6230,
    likes: 512,
    tags: ['手表', '商务', '磁吸', '礼盒'],
    category: 'model',
    boxType: 'gift',
    price: '¥299-1999',
    material: '磁吸纸板+PU',
    industry: '钟表',
  },
  {
    id: 'box-11',
    title: '🎀 巧克力礼盒',
    description: '手工巧克力礼盒，多格分区设计，精美丝带装饰',
    thumbnail: 'https://picsum.photos/seed/gift3/400/300',
    modelUrl: '',
    author: 'User Demo',
    createdAt: '2026-04-11',
    views: 4120,
    likes: 356,
    tags: ['巧克力', '甜品', '丝带', '手工'],
    category: 'model',
    boxType: 'gift',
    price: '¥99-499',
    material: '白卡+覆膜+丝带',
    industry: '食品',
  },
  {
    id: 'box-12',
    title: '🌺 永生花礼盒',
    description: '永生花+香水套装盒，浪漫粉配色，情侣礼物首选',
    thumbnail: 'https://picsum.photos/seed/gift4/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-09',
    views: 5340,
    likes: 467,
    tags: ['永生花', '花艺', '浪漫', '情侣'],
    category: 'model',
    boxType: 'gift',
    price: '¥199-799',
    material: '特种纸+烫金',
    industry: '花艺',
  },

  // ========== 食品盒 ==========
  {
    id: 'box-13',
    title: '🍫 月饼礼盒',
    description: '中秋月饼礼盒，国潮设计风格，传统与时尚结合',
    thumbnail: 'https://picsum.photos/seed/food1/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-17',
    views: 8560,
    likes: 723,
    tags: ['月饼', '中秋', '国潮', '传统'],
    category: 'model',
    boxType: 'food',
    price: '¥99-599',
    material: '特种纸+UV+烫金',
    industry: '食品',
  },
  {
    id: 'box-14',
    title: '🍵 茶叶礼盒',
    description: '高档茶叶礼盒，古风设计，武夷岩茶/普洱套装',
    thumbnail: 'https://picsum.photos/seed/food2/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-14',
    views: 6230,
    likes: 534,
    tags: ['茶叶', '茶具', '古风', '养生'],
    category: 'model',
    boxType: 'food',
    price: '¥199-999',
    material: '竹木+特种纸',
    industry: '食品',
  },
  {
    id: 'box-15',
    title: '🍯 蜂蜜礼盒',
    description: '天然蜂蜜礼盒，森系包装设计，纯天然无添加',
    thumbnail: 'https://picsum.photos/seed/food3/400/300',
    modelUrl: '',
    author: 'User Demo',
    createdAt: '2026-04-12',
    views: 3890,
    likes: 312,
    tags: ['蜂蜜', '天然', '森系', '健康'],
    category: 'model',
    boxType: 'food',
    price: '¥89-399',
    material: '牛皮纸+木盒',
    industry: '食品',
  },
  {
    id: 'box-16',
    title: '🥮 粽子礼盒',
    description: '端午粽子礼盒，清新绿色调，传统节日美食',
    thumbnail: 'https://picsum.photos/seed/food4/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-10',
    views: 2890,
    likes: 234,
    tags: ['粽子', '端午', '传统', '节日'],
    category: 'model',
    boxType: 'food',
    price: '¥79-299',
    material: '竹编+特种纸',
    industry: '食品',
  },
  {
    id: 'box-17',
    title: '🍬 糖果礼盒',
    description: '手工糖果礼盒，马卡龙色系，梦幻少女风格',
    thumbnail: 'https://picsum.photos/seed/food5/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-08',
    views: 3450,
    likes: 289,
    tags: ['糖果', '甜品', '少女', '梦幻'],
    category: 'model',
    boxType: 'food',
    price: '¥69-259',
    material: '白卡+覆膜+丝带',
    industry: '食品',
  },

  // ========== 节日礼盒 ==========
  {
    id: 'box-18',
    title: '🧧 春节礼盒',
    description: '新年礼盒套装，中国红+烫金工艺，喜庆吉祥',
    thumbnail: 'https://picsum.photos/seed/festival1/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-16',
    views: 9230,
    likes: 812,
    tags: ['春节', '新年', '中国红', '喜庆'],
    category: 'model',
    boxType: 'festival',
    price: '¥199-899',
    material: '特种纸+烫金UV',
    industry: '综合',
  },
  {
    id: 'box-19',
    title: '🎄 圣诞礼盒',
    description: '圣诞主题礼盒，红色+金色配色，节日气氛浓厚',
    thumbnail: 'https://picsum.photos/seed/festival2/400/300',
    modelUrl: '',
    author: 'User Demo',
    createdAt: '2026-04-14',
    views: 5670,
    likes: 478,
    tags: ['圣诞', '节日', '红色', '礼品'],
    category: 'model',
    boxType: 'festival',
    price: '¥99-499',
    material: '特种纸+烫金',
    industry: '综合',
  },
  {
    id: 'box-20',
    title: '💝 情人节礼盒',
    description: '情侣礼物套装，心形元素+玫瑰金，浪漫氛围',
    thumbnail: 'https://picsum.photos/seed/festival3/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-13',
    views: 7890,
    likes: 689,
    tags: ['情人节', '情侣', '浪漫', '玫瑰金'],
    category: 'model',
    boxType: 'festival',
    price: '¥199-999',
    material: '特种纸+烫金+丝带',
    industry: '综合',
  },
  {
    id: 'box-21',
    title: '🎃 万圣节礼盒',
    description: '万圣节主题礼盒，暗黑系配色，南瓜元素',
    thumbnail: 'https://picsum.photos/seed/festival4/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-11',
    views: 3450,
    likes: 278,
    tags: ['万圣节', '暗黑', '南瓜', '趣味'],
    category: 'model',
    boxType: 'festival',
    price: '¥79-399',
    material: '黑卡+UV',
    industry: '综合',
  },
  {
    id: 'box-22',
    title: '🐲 端午礼盒',
    description: '端午节日套装，龙舟+祥云图案，传统文化',
    thumbnail: 'https://picsum.photos/seed/festival5/400/300',
    modelUrl: '',
    author: 'User Demo',
    createdAt: '2026-04-09',
    views: 4120,
    likes: 345,
    tags: ['端午', '龙舟', '传统', '节日'],
    category: 'model',
    boxType: 'festival',
    price: '¥129-599',
    material: '竹编+特种纸',
    industry: '综合',
  },
  {
    id: 'box-23',
    title: '🌸 母亲节礼盒',
    description: '母亲节感恩礼盒，温馨粉色+康乃馨图案',
    thumbnail: 'https://picsum.photos/seed/festival6/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-07',
    views: 5230,
    likes: 456,
    tags: ['母亲节', '感恩', '温馨', '康乃馨'],
    category: 'model',
    boxType: 'festival',
    price: '¥159-799',
    material: '特种纸+烫银',
    industry: '综合',
  },

  // ========== 烟酒礼盒 ==========
  {
    id: 'box-24',
    title: '🚬 高档香烟礼盒',
    description: '精品香烟礼盒，中国风设计，限量版收藏',
    thumbnail: 'https://picsum.photos/seed/tobacco1/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-15',
    views: 6890,
    likes: 567,
    tags: ['香烟', '烟草', '限量', '收藏'],
    category: 'model',
    boxType: 'festival',
    price: '¥399-1999',
    material: '特种纸+烫金+木盒',
    industry: '烟草',
  },
  {
    id: 'box-25',
    title: '🎉 年货礼盒套装',
    description: '过年礼品大礼包，红色喜庆包装，干果腊味组合',
    thumbnail: 'https://picsum.photos/seed/tobacco2/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-12',
    views: 7890,
    likes: 623,
    tags: ['年货', '春节', '干果', '礼包'],
    category: 'model',
    boxType: 'festival',
    price: '¥199-899',
    material: '瓦楞纸+特种纸',
    industry: '食品',
  },
  {
    id: 'box-26',
    title: '🎊 中秋月饼酒水礼盒',
    description: '中秋节月饼+酒水组合礼盒，一盒搞定送礼需求',
    thumbnail: 'https://picsum.photos/seed/tobacco3/400/300',
    modelUrl: '',
    author: 'User Demo',
    createdAt: '2026-04-10',
    views: 6230,
    likes: 512,
    tags: ['中秋', '月饼', '酒水', '组合'],
    category: 'model',
    boxType: 'festival',
    price: '¥299-1299',
    material: '木质+特种纸',
    industry: '综合',
  },

  // ========== 电子产品盒 ==========
  {
    id: 'box-27',
    title: '📱 手机礼盒',
    description: '旗舰手机礼盒，环保可回收材料，极简设计',
    thumbnail: 'https://picsum.photos/seed/elec1/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-14',
    views: 4560,
    likes: 389,
    tags: ['手机', '数码', '环保', '极简'],
    category: 'model',
    boxType: 'electronics',
    price: '¥99-299',
    material: '环保纸+大豆油墨',
    industry: '数码',
  },
  {
    id: 'box-28',
    title: '🎧 耳机礼盒',
    description: '降噪耳机礼盒，科技感设计，高端礼品选择',
    thumbnail: 'https://picsum.photos/seed/elec2/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-12',
    views: 3890,
    likes: 312,
    tags: ['耳机', '数码', '科技', '礼品'],
    category: 'model',
    boxType: 'electronics',
    price: '¥79-399',
    material: '特种纸+磁吸',
    industry: '数码',
  },

  // ========== 服饰盒 ==========
  {
    id: 'box-29',
    title: '👔 领带礼盒',
    description: '高档领带礼盒，丝绸质感内衬，商务男士首选',
    thumbnail: 'https://picsum.photos/seed/fashion1/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-13',
    views: 3450,
    likes: 289,
    tags: ['领带', '服饰', '商务', '丝绸'],
    category: 'model',
    boxType: 'fashion',
    price: '¥199-799',
    material: '木板+丝绸',
    industry: '服装',
  },
  {
    id: 'box-30',
    title: '👜 皮具礼盒套装',
    description: '真皮皮具礼盒，手工缝制，奢华商务风格',
    thumbnail: 'https://picsum.photos/seed/fashion2/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-11',
    views: 5230,
    likes: 445,
    tags: ['皮具', '真皮', '奢华', '手工'],
    category: 'model',
    boxType: 'fashion',
    price: '¥399-1999',
    material: '真皮+金属配件',
    industry: '皮具',
  },
  {
    id: 'box-31',
    title: '🧣 丝巾礼盒',
    description: '真丝丝巾礼盒，东方印花设计，艺术收藏品',
    thumbnail: 'https://picsum.photos/seed/fashion3/400/300',
    modelUrl: '',
    author: 'User Demo',
    createdAt: '2026-04-09',
    views: 4120,
    likes: 356,
    tags: ['丝巾', '真丝', '印花', '艺术'],
    category: 'model',
    boxType: 'fashion',
    price: '¥299-1299',
    material: '真丝+特种纸盒',
    industry: '服装',
  },
];

// ==================== 3D模型类 ====================
const THREE_D_MODELS: GalleryItem[] = [
  {
    id: '3d-1',
    title: '🦋 Butterfly 3DGS',
    description: '使用手机拍摄照片重建的蝴蝶模型，精细到翅膀纹理和鳞粉效果',
    thumbnail: 'https://picsum.photos/seed/butterfly3d/400/300',
    gifPreview: 'https://media.giphy.com/media/3o7TKP0tZ2cN5ycQk8/giphy.gif',
    modelUrl: 'https://sparkjs.dev/assets/splats/butterfly.spz',
    author: 'SmartAI Team',
    createdAt: '2026-04-15',
    views: 3450,
    likes: 289,
    tags: ['蝴蝶', '昆虫', '自然', '精细'],
    category: 'model',
  },
  {
    id: '3d-2',
    title: '🐉 Dragon Sculpture',
    description: '传统文化雕塑的3DGS数字化，完美保留所有细节和色彩',
    thumbnail: 'https://picsum.photos/seed/dragon3d/400/300',
    gifPreview: 'https://media.giphy.com/media/26u4cqiYI30juCOGY/giphy.gif',
    modelUrl: 'https://sparkjs.dev/assets/splats/dragon.spz',
    author: 'SmartAI Team',
    createdAt: '2026-04-12',
    views: 5230,
    likes: 456,
    tags: ['龙', '雕塑', '文化', '传统'],
    category: 'model',
  },
  {
    id: '3d-3',
    title: '🚗 Vintage Car',
    description: '经典老爷车3DGS重建，完美还原车身曲线和金属质感',
    thumbnail: 'https://picsum.photos/seed/vintagecar/400/300',
    gifPreview: 'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-08',
    views: 8200,
    likes: 645,
    tags: ['汽车', '老爷车', '工业', '复古'],
    category: 'model',
  },
  {
    id: '3d-4',
    title: '👤 Human Portrait',
    description: '人物肖像3DGS重建，精细到皮肤纹理和表情细节',
    thumbnail: 'https://picsum.photos/seed/human3d/400/300',
    gifPreview: 'https://media.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-03-28',
    views: 12500,
    likes: 980,
    tags: ['人像', '肖像', '人物', '高精度'],
    category: 'model',
  },
];

// ==================== 场景类 ====================
const SCENE_MODELS: GalleryItem[] = [
  {
    id: 'scene-1',
    title: '🏙️ City Street Scene',
    description: '城市街景3DGS重建，适合AR导航和虚拟旅游',
    thumbnail: 'https://picsum.photos/seed/street3d/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-10',
    views: 4890,
    likes: 367,
    tags: ['城市', '街景', '建筑', 'AR'],
    category: 'scene',
  },
  {
    id: 'scene-2',
    title: '🏛️ Ancient Temple',
    description: '古建筑三维数字化，精度达到毫米级，保留历史痕迹',
    thumbnail: 'https://picsum.photos/seed/temple3d/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-02',
    views: 6100,
    likes: 492,
    tags: ['寺庙', '古建筑', '文化遗产', '高精度'],
    category: 'scene',
  },
  {
    id: 'scene-3',
    title: '⛰️ Mountain Landscape',
    description: '山岳景观大场景重建，适合游戏和VR应用',
    thumbnail: 'https://picsum.photos/seed/mountain3d/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-03-25',
    views: 4650,
    likes: 334,
    tags: ['山脉', '风景', '自然', 'VR'],
    category: 'scene',
  },
  {
    id: 'scene-4',
    title: '🏠 Interior Room',
    description: '室内房间3DGS场景，支持实时光照调整',
    thumbnail: 'https://picsum.photos/seed/room3d/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-03-22',
    views: 7230,
    likes: 580,
    tags: ['室内', '房间', '家居', '装修'],
    category: 'scene',
  },
];

// ==================== 动画类 ====================
const ANIMATION_MODELS: GalleryItem[] = [
  {
    id: 'anim-1',
    title: '🌸 Flower Garden',
    description: '花园场景动态展示，花朵随风摇曳效果生动',
    thumbnail: 'https://picsum.photos/seed/flowergarden/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-04-05',
    views: 7890,
    likes: 678,
    tags: ['花园', '花朵', '自然', '动态'],
    category: 'animation',
  },
  {
    id: 'anim-2',
    title: '🌊 Ocean Wave',
    description: '海浪动态3DGS展示，波浪起伏效果逼真',
    thumbnail: 'https://picsum.photos/seed/oceanwave/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-03-28',
    views: 9120,
    likes: 780,
    tags: ['海洋', '波浪', '动态', '自然'],
    category: 'animation',
  },
  {
    id: 'anim-3',
    title: '🔥 Fireworks Show',
    description: '烟花动画3DGS效果，璀璨夜空表演',
    thumbnail: 'https://picsum.photos/seed/fireworks3d/400/300',
    modelUrl: '',
    author: 'User Demo',
    createdAt: '2026-03-25',
    views: 13400,
    likes: 1120,
    tags: ['烟花', '动画', '节日', '夜空'],
    category: 'animation',
  },
  {
    id: 'anim-4',
    title: '🍃 Autumn Leaves',
    description: '秋叶飘落动画场景，树叶旋转下落效果',
    thumbnail: 'https://picsum.photos/seed/autumn3d/400/300',
    modelUrl: '',
    author: 'SmartAI Team',
    createdAt: '2026-03-22',
    views: 5670,
    likes: 445,
    tags: ['秋天', '落叶', '动画', '季节'],
    category: 'animation',
  },
];

// 合并所有数据
export const GALLERY_ITEMS: GalleryItem[] = [
  ...BOX_MODELS,
  ...THREE_D_MODELS,
  ...SCENE_MODELS,
  ...ANIMATION_MODELS,
];

// 分类配置
export const CATEGORIES = [
  { value: 'all', label: '全部', icon: '🎨' },
  { value: 'box', label: '精品盒', icon: '📦' },
  { value: 'model', label: '3D模型', icon: '🪆' },
  { value: 'scene', label: '场景', icon: '🏞️' },
  { value: 'animation', label: '动画', icon: '🎬' },
] as const;

// 盒子子分类
export const BOX_CATEGORIES = [
  { value: 'all', label: '全部盒子', icon: '📦' },
  { value: 'cosmetics', label: '💄 化妆品盒', icon: '💄' },
  { value: 'wine', label: '🍷 酒盒', icon: '🍷' },
  { value: 'gift', label: '🎁 礼品盒', icon: '🎁' },
  { value: 'food', label: '🍱 食品盒', icon: '🍱' },
  { value: 'festival', label: '🎊 节日礼盒', icon: '🎊' },
  { value: 'electronics', label: '📱 电子产品盒', icon: '📱' },
  { value: 'fashion', label: '👔 服饰盒', icon: '👔' },
] as const;
